/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include <FreeRTOS.h>
#include <task.h>
#include <stdio.h>

#include "bsp/kit_tc4d7_lite.h"

#include "Cpu/Irq/IfxCpu_Irq.h"
#include "Cpu/Std/IfxCpu.h"
#include "Wtu/Std/IfxWtu.h"

#include "Egtm/Std/IfxEgtm.h"
#include "Egtm/Std/IfxEgtm_Cmu.h"
#include "Egtm/Std/IfxEgtm_Tom.h"
#include "Src/Std/IfxSrc.h"

#include "retarget_io/retarget_io.h"


/*******************************************************************************
* Macros
*******************************************************************************/
#define BLINKY_TASK_STACK_SIZE          (configMINIMAL_STACK_SIZE)
#define PRINT_TASK_STACK_SIZE           (configMINIMAL_STACK_SIZE * 2U)
#define BLINKY_TASK_PRIORITY            (tskIDLE_PRIORITY + 1U)
#define PRINT_TASK_PRIORITY             (tskIDLE_PRIORITY + 2U)

#define LED1_TOGGLE_PERIOD_MS           500U
#define BUTTON_POLL_PERIOD_MS           20U
#define TOM_TIMER_FREQUENCY_HZ          1UL
#define TOM_TIMER_ISR_PRIORITY          31
#define TOM_TIMER_CLUSTER               ((IfxEgtm_Cluster)0)
#define TOM_TIMER_CHANNEL               IfxEgtm_Tom_Ch_0


/*******************************************************************************
* Type definitions
*******************************************************************************/

/*******************************************************************************
* Function Prototypes
*******************************************************************************/
static void blinky_task(void *pvParameters);
static void print_task(void *pvParameters);
static void init_board(void);
static void init_egtm_tom_timer(void);

IFX_INTERRUPT(egtm_tom_timer_isr, 0, TOM_TIMER_ISR_PRIORITY);

/*******************************************************************************
* Global Variables
*******************************************************************************/
static TaskHandle_t g_printTaskHandle = NULL;
static Ifx_EGTM_CLS_TOM *g_tom = NULL;

/*******************************************************************************
* Function Name: core0_main
********************************************************************************
* Summary:
* This is the main function for core0.
*
* Parameters:
*  none
*
* Return:
*  none
*
*******************************************************************************/
void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());
    
    /**************************************************************************************************/
    /* Board resources initialization */

    init_board();

    /**************************************************************************************************/
    /* Demo execution */

    printf("******** TC4D7_lite_kit: FreeRTOS eGTM TOM Printf Demo ********\r\n\n");

    BaseType_t xReturned = xTaskCreate(blinky_task,
                                       "Blinky",
                                       BLINKY_TASK_STACK_SIZE,
                                       NULL,
                                       BLINKY_TASK_PRIORITY,
                                       NULL);
    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, xReturned == pdPASS);

    xReturned = xTaskCreate(print_task,
                            "Print",
                            PRINT_TASK_STACK_SIZE,
                            NULL,
                            PRINT_TASK_PRIORITY,
                            &g_printTaskHandle);
    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, xReturned == pdPASS);

    init_egtm_tom_timer();

    vTaskStartScheduler();

    /* Should never reach here. */
    for( ; ; );
}

/*******************************************************************************
* Function Name: init_board
********************************************************************************
* Summary:
* Initialize board IO used by the demo.
*
* Parameters:
*  none
*
* Return:
*  none
*
*******************************************************************************/
static void init_board(void)
{
    IfxPort_setPinHigh(BOARD_USER_LED_1.port, BOARD_USER_LED_1.pinIndex);
    IfxPort_setPinLow(BOARD_USER_LED_2.port, BOARD_USER_LED_2.pinIndex);

    IfxPort_setPinModeOutput(BOARD_USER_LED_1.port,
                             BOARD_USER_LED_1.pinIndex,
                             IfxPort_OutputMode_pushPull,
                             IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(BOARD_USER_LED_2.port,
                             BOARD_USER_LED_2.pinIndex,
                             IfxPort_OutputMode_pushPull,
                             IfxPort_OutputIdx_general);
    IfxPort_setPinModeInput(BOARD_USER_BUTTON_1.port,
                            BOARD_USER_BUTTON_1.pinIndex,
                            IfxPort_InputMode_pullUp);

    if (retarget_io_init(&BOARD_DEBUG_UART_TX, &BOARD_DEBUG_UART_RX, 115200) != 0)
    {
        IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, 0);
    }
}

/*******************************************************************************
* Function Name: blinky_task
********************************************************************************
* Summary:
* Toggle LED1 cyclically and toggle LED2 on each BUTTON1 press.
*
* Parameters:
*  none
*
* Return:
*  none
*
*******************************************************************************/
static void blinky_task(void *pvParameters)
{
    TickType_t xLastWakeTime = xTaskGetTickCount();
    uint32 ledElapsedMs = 0U;
    boolean wasButtonPressed = FALSE;

    (void)pvParameters;

    while (1)
    {
        boolean isButtonPressed = (IfxPort_getPinState(BOARD_USER_BUTTON_1.port,
                                                       BOARD_USER_BUTTON_1.pinIndex) == FALSE);

        if ((isButtonPressed != FALSE) && (wasButtonPressed == FALSE))
        {
            IfxPort_togglePin(BOARD_USER_LED_2.port, BOARD_USER_LED_2.pinIndex);
        }

        wasButtonPressed = isButtonPressed;
        ledElapsedMs += BUTTON_POLL_PERIOD_MS;

        if (ledElapsedMs >= LED1_TOGGLE_PERIOD_MS)
        {
            IfxPort_togglePin(BOARD_USER_LED_1.port, BOARD_USER_LED_1.pinIndex);
            ledElapsedMs = 0U;
        }

        vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(BUTTON_POLL_PERIOD_MS));
    }
}

/*******************************************************************************
* Function Name: print_task
********************************************************************************
* Summary:
* Wait for task notifications from the eGTM TOM ISR and print a message.
*
* Parameters:
*  none
*
* Return:
*  none
*
*******************************************************************************/
static void print_task(void *pvParameters)
{
    uint32 notificationCount;

    (void)pvParameters;

    while (1)
    {
        notificationCount = ulTaskNotifyTake(pdTRUE, portMAX_DELAY);

        if (notificationCount > 0U)
        {
            printf("eGTM TOM timer interrupt notified print task\r\n");
        }
    }
}

/*******************************************************************************
* Function Name: init_egtm_tom_timer
********************************************************************************
* Summary:
* Initialize the eGTM TOM timer used to periodically notify the print task.
*
* Parameters:
*  none
*
* Return:
*  none
*
*******************************************************************************/
static void init_egtm_tom_timer(void)
{
    float32 moduleFrequency;
    float32 fxClockFrequency;
    uint32 period;
    volatile Ifx_SRC_SRCR *src;
    Ifx_EGTM_CLS_TOM_TGC *tgc;

    IfxEgtm_enable(&MODULE_EGTM);

    moduleFrequency = IfxEgtm_Cmu_getModuleFrequency(&MODULE_EGTM);
    IfxEgtm_Cmu_setGclkFrequency(&MODULE_EGTM, moduleFrequency);
    IfxEgtm_Cmu_enableClocks(&MODULE_EGTM, IFXEGTM_CMU_CLKEN_FXCLK);

    g_tom = &MODULE_EGTM.CLS[TOM_TIMER_CLUSTER].TOM;

    IfxEgtm_Tom_Ch_setClockSource(g_tom,
                                  TOM_TIMER_CHANNEL,
                                  IfxEgtm_Tom_Ch_ClkSrc_cmuFxclk4);

    fxClockFrequency = moduleFrequency / 32768.0f;
    period = (uint32)(fxClockFrequency / (float32)TOM_TIMER_FREQUENCY_HZ);

    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, (period > 0U) && (period <= 0xFFFFU));

    IfxEgtm_Tom_Ch_setCompareZeroShadow(g_tom, TOM_TIMER_CHANNEL, (uint16)period);
    IfxEgtm_Tom_Ch_setCounterValue(g_tom, TOM_TIMER_CHANNEL, 0U);
    IfxEgtm_Tom_Ch_setTriggerOutput(g_tom,
                                    TOM_TIMER_CHANNEL,
                                    IfxEgtm_Tom_Ch_OutputTrigger_generate);
    IfxEgtm_Tom_Ch_setNotification(g_tom,
                                   TOM_TIMER_CHANNEL,
                                   IfxEgtm_IrqMode_pulseNotify,
                                   TRUE,
                                   FALSE);

    src = IfxEgtm_Tom_Ch_getSrcPointer(&MODULE_EGTM,
                                       TOM_TIMER_CLUSTER,
                                       TOM_TIMER_CHANNEL);
    IfxSrc_init(src, IfxSrc_Tos_cpu0, (Ifx_Priority)TOM_TIMER_ISR_PRIORITY, (IfxSrc_VmId)configVM_NR);
    IfxSrc_enable(src);

    tgc = IfxEgtm_Tom_Ch_getTgcPointer(g_tom, 0U);

    IfxEgtm_Tom_Tgc_setChannelsForceUpdate(tgc, 1U << 0, 0U, 0U, 0U);
    IfxEgtm_Tom_Tgc_trigger(tgc);
    IfxEgtm_Tom_Tgc_setChannelsForceUpdate(tgc, 0U, 1U << 0, 0U, 0U);

    IfxEgtm_Tom_Ch_clearZeroNotification(g_tom, TOM_TIMER_CHANNEL);
    IfxEgtm_Tom_Tgc_enableChannels(tgc, 1U << 0, 0U, TRUE);
}

/*******************************************************************************
* Function Name: egtm_tom_timer_isr
********************************************************************************
* Summary:
* Handle the eGTM TOM timer interrupt and wake the print task.
*
* Parameters:
*  none
*
* Return:
*  none
*
*******************************************************************************/
void egtm_tom_timer_isr(void)
{
    BaseType_t xHigherPriorityTaskWoken = pdFALSE;

    if (IfxEgtm_Tom_Ch_isZeroNotification(g_tom, TOM_TIMER_CHANNEL) != FALSE)
    {
        IfxEgtm_Tom_Ch_clearZeroNotification(g_tom, TOM_TIMER_CHANNEL);

        if (g_printTaskHandle != NULL)
        {
            vTaskNotifyGiveFromISR(g_printTaskHandle, &xHigherPriorityTaskWoken);
            portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
        }
    }
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;
    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, 0);
}
