/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *
 * SPDX-License-Identifier: BSL-1.0
 *********************************************************************************************************************/

#include <stdio.h>

#include "bsp/kit_tc4d7_lite.h"

#include "Cpu/Std/IfxCpu.h"
#include "Wtu/Std/IfxWtu.h"
#include "Stm/Std/IfxStm.h"

#include "retarget_io/retarget_io.h"

#include "FreeRTOS.h"
#include "task.h"

/*******************************************************************************
* Macros
*******************************************************************************/
/* LED toggle period in milliseconds */
#define LED_TOGGLE_MS           500


/*******************************************************************************
* Type definitions
*******************************************************************************/

/*******************************************************************************
* Function Prototypes
*******************************************************************************/
static void led_task(void* pvParameters);

/*******************************************************************************
* Global Variables
*******************************************************************************/

/*******************************************************************************
* Function Name: core0_main
********************************************************************************
* Summary:
* This is the main function for core0.
*
* Parameters:
*  none
*
* Return:
*  none
*
*******************************************************************************/
void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());
    
    /**************************************************************************************************/
    /* Board resources initialization */

    IfxPort_setPinHigh(BOARD_USER_LED_1.port, BOARD_USER_LED_1.pinIndex);
    IfxPort_setPinModeOutput(BOARD_USER_LED_1.port, BOARD_USER_LED_1.pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

    if (retarget_io_init(&BOARD_DEBUG_UART_TX, &BOARD_DEBUG_UART_RX, 115200) != 0)
    {
        IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, 0);
    }

    /**************************************************************************************************/
    /* Demo execution */

    printf("******** TC4D7_lite_kit: FreeRTOS blinky Demo ********\r\n\n");

    /* Create task. */
    BaseType_t xReturned = xTaskCreate(led_task, "LED_Task", configMINIMAL_STACK_SIZE, NULL, tskIDLE_PRIORITY, NULL);
    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, xReturned == pdPASS);

    vTaskStartScheduler();

    /* Should never reach here. */
    for( ; ; );
}

/*******************************************************************************
* Function Name: led_task
********************************************************************************
* Summary:
* This is the led task that toggles the BOARD_USER_LED every LED_TIMER_PERIOD_MS
*
* Parameters:
*  none
*
* Return:
*  none
*
*******************************************************************************/
static void led_task(void* pvParameters)
{
    (void)pvParameters;

    while (1)
    {
        /* Block the task for the defined time */
        vTaskDelay(LED_TOGGLE_MS / portTICK_PERIOD_MS);

        IfxPort_togglePin(BOARD_USER_LED_1.port, BOARD_USER_LED_1.pinIndex);
    }
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, 0);
}
